github.com:
    users:
        cruzperezm:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: cruzperezm
